[plants]
cohort_data_path = "../data_single_grid/plant_cohort_data_Maliau_50x50.csv"
pft_definitions_path = "../data_single_grid/plant_pft_definitions_Maliau_50x50.csv"

[plants.community_data_export]
required_data = ["cohorts","community_canopy","stem_canopy"]
cohort_attributes = []
community_canopy_attributes = []
stem_canopy_attributes = []
float_format = "%0.5f"

# Plant data
[[core.data.variable]]
file_path = "../data_single_grid/plant_input_data_Maliau_50x50.nc"
var_name = "plant_pft_propagules"
[[core.data.variable]]
file_path = "../data_single_grid/plant_input_data_Maliau_50x50.nc"
var_name = "subcanopy_vegetation_biomass"
[[core.data.variable]]
file_path = "../data_single_grid/plant_input_data_Maliau_50x50.nc"
var_name = "subcanopy_seedbank_biomass"

[plants.constants]
per_stem_annual_mortality_probability = 0.0159
per_propagule_annual_recruitment_probability = 0.025
dsr_to_ppfd = 2.04
stem_lignin = 0.31318082788671
senesced_leaf_lignin = 0.29
plant_reproductive_tissue_lignin = 0.177795337811142
root_lignin = 0.304203539823009
subcanopy_extinction_coef = 0.48
subcanopy_specific_leaf_area = 56.7498434446958
subcanopy_respiration_fraction = 0.132
subcanopy_yield = 0.68
subcanopy_reproductive_allocation = 0.223545331529093
subcanopy_sprout_rate = 0.68
subcanopy_sprout_yield = 0.68
subcanopy_vegetation_turnover = 2.57142857142857
subcanopy_seedbank_turnover = 0.32
subcanopy_seedbank_c_n_ratio = 37.1222841063908
subcanopy_seedbank_c_p_ratio = 598.922484461952
subcanopy_vegetation_c_n_ratio = 17.2010712814174
subcanopy_vegetation_c_p_ratio = 206.668316831683
subcanopy_vegetation_lignin = 0.291937145184085
subcanopy_seedbank_lignin = 0.177795337811142
root_exudates = 0.0201055284
propagule_mass_portion = 0.773915715
carbon_mass_per_propagule = 1.179446
